In [1]:
import sys
import os
import pandas as pd
import numpy as np
import warnings
import scipy.stats as st
import glob
import re
source_path = os.path.abspath(os.path.join(os.getcwd(), '..', '..'))
sys.path.append(source_path)

warnings.filterwarnings('ignore')

In [4]:
experiment_csv = os.path.join('experiment_tables', "experiment_table_20251111_113627.pkl")
df_experiments = pd.read_pickle(experiment_csv)  # Use read_csv if the file is in CSV format
folder='outputs' 
feature_files = glob.glob(os.path.join(folder, "*.json"))
print(feature_files)
df_pre_patch, df_pre_extracted, df_pre_contrastive, df_pre_handcrafted = file_IO.preprocess_experiment_logs(source_path)
df_visualization = file_IO.get_reference_table_for_experiments(df_pre_patch, df_pre_extracted, im_show=False,im_plot=False)

['outputs\\results_standard_body.json', 'outputs\\results_standard_patches.json', 'outputs\\results_standard_patches_generalization.json', 'outputs\\results_standard_patches_no_scaling.json', 'outputs\\results_standard_patches_single.json', 'outputs\\test_standard_patches.json', 'outputs\\test_standard_patches_no_scaling.json']

In [5]:
all_ensembling_approaches = ['individual','ensembled','ensembled_weighted','ensembled_most_probable','ensembled_writers']
best_metric='ensembled_weighted'
all_groups=['english,different',
 'english,same',
 'arabic,different',
 'arabic,same',
 'english,all',
 'arabic,all',
 'all,different',
 'all,same']
IF_OOF = ['IF','OOF']
all_metrics = ['Mean','Min','Max','Variance','Median','Confidence Interval','Generalization Gap']
experiment_results={}

# standard patches

In [6]:
experiment='outputs\\results_standard_patches.json'

In [7]:
df_standard_patches=process_results(experiment, df_pre_patch,name_suffix='standard',box_and_whiskers=False)
experiment_results['standard_patches'] = df_standard_patches

In [8]:
setting_display_options()
display(df_standard_patches.sort_values(by='accuracies_standard', ascending=False))
save_table_as_image(df_standard_patches,by_column='accuracies_standard',significant_digits=4)

,FE model,accuracies_standard,accuracies_std_standard,ind_accuracies_standard,ind_accuracies_std_standard
71,clip-vit-large-patch14-inter,0.774015,0.051471,0.740062,0.033951
63,BEiT-Large,0.767826,0.061211,0.718713,0.047689
64,BEiT-Large-inter,0.766041,0.051911,0.729649,0.037044
22,BEiT-Base,0.765025,0.055745,0.711188,0.036050
73,trocr-large-handwritten-inter,0.752555,0.052081,0.693836,0.042002
25,clip-vit-large-patch14-un,0.741010,0.044030,0.685979,0.045204
46,convnext_large,0.734883,0.061863,0.698615,0.041903
74,trocr-large-stage1-inter,0.734144,0.070820,0.694310,0.049490
23,clip-vit-base-patch16,0.730388,0.045668,0.677531,0.045884
19,DeiT-Small,0.730357,0.051938,0.673528,0.039391
18,swin_s,0.729526,0.062252,0.687377,0.044621
45,efficientnet_v2_s,0.727894,0.061601,0.689680,0.052321
70,convnext_large-inter,0.727802,0.052981,0.700117,0.043353
13,trocr-large-stage1,0.724969,0.064788,0.689101,0.056321
47,convnext_base,0.724415,0.076435,0.690203,0.053959
17,swin_b,0.723337,0.058295,0.690659,0.046705
5,clip-vit-large-patch14,0.723307,0.033247,0.692605,0.037414
26,vit-base-patch16-224,0.721829,0.045587,0.660764,0.035632
48,convnext_small,0.718812,0.049091,0.690339,0.044065
34,linknet_resnet18,0.716810,0.064331,0.684366,0.045758
7,dresnet50,0.715148,0.050710,0.663356,0.045230
20,DeiT-Small-Dist,0.713300,0.049624,0.668165,0.043527
3,vit-base-patch16-224-in21k,0.712685,0.040415,0.667488,0.042831
6,trocr-large-handwritten,0.711700,0.048113,0.663510,0.047219
14,trocr-base-stage1,0.710037,0.036919,0.678584,0.043617
56,regnet_x_32,0.709236,0.062118,0.659963,0.047352
69,dresnet50-inter,0.709052,0.049691,0.683947,0.047230
50,mobilenet_v3_large,0.708744,0.074062,0.664828,0.055492
44,efficientnet_v2_l,0.706312,0.042903,0.671361,0.039950
29,vit-huge-patch14-224-in21k,0.706158,0.059311,0.685751,0.042826
76,crnn_vgg16_bn_224-inter,0.704495,0.068534,0.681170,0.060752
52,resnet34_layer2,0.701786,0.062526,0.671201,0.057839
27,vit-base-patch32-224-in21k,0.698399,0.028605,0.671712,0.030933
21,DeiT-Base,0.697660,0.020155,0.651059,0.018927
28,vit-large-patch16-224-in21k,0.696798,0.046043,0.667371,0.026762
62,linknet_resnet50,0.693103,0.051261,0.664107,0.049212
60,regnet_y_3_2,0.693042,0.058527,0.644070,0.051154
59,regnet_y_32,0.691533,0.056980,0.652469,0.046400
75,DeiT-Tiny-inter,0.690425,0.051063,0.662580,0.045622
40,densenet201,0.689840,0.057988,0.645677,0.037803
24,clip-vit-base-patch32,0.689501,0.041031,0.656361,0.035622
2,resnet50,0.688608,0.056224,0.643288,0.039782
51,resnet34_layer3,0.684975,0.071525,0.658768,0.048379
16,DeiT-Tiny,0.684083,0.060543,0.647315,0.045750
58,regnet_y_128,0.683528,0.049835,0.631459,0.032355
43,maxvit,0.683436,0.068781,0.646952,0.051936
54,resnet101,0.682574,0.059557,0.650179,0.047928
49,mobilenet_v3_small,0.680388,0.065858,0.647365,0.052892
66,crnn_vgg16_bn_224,0.679526,0.093259,0.641958,0.075816
61,inception_net,0.678879,0.050632,0.629027,0.043898
38,densenet161,0.678110,0.070751,0.636281,0.044350
39,densenet121,0.677001,0.069482,0.639514,0.046574
41,vgg11,0.670782,0.062349,0.639009,0.060769
72,crnn_mobilenet_224-inter,0.670751,0.056131,0.646176,0.051307
57,regnet_x_3_2,0.670720,0.057820,0.623929,0.040948
42,vgg16_512,0.668966,0.074452,0.634212,0.050338
33,linknet_resnet50_224,0.666349,0.056514,0.612457,0.051629
55,resnet34,0.665456,0.062880,0.610400,0.047225
53,resnet34_layer1,0.664932,0.053666,0.649113,0.048336
31,db_mobilenet,0.664717,0.056248,0.643898,0.043428
4,trocr-base-handwritten,0.664563,0.065464,0.648744,0.050904
37,alexnet_gap,0.663670,0.075532,0.624643,0.047010
12,googlenet,0.663547,0.078984,0.625708,0.056641
30,vitstr_small,0.653910,0.046466,0.612654,0.036995
65,sar_resnet31_224,0.647814,0.075329,0.625844,0.056769
32,crnn_mobilenet_224,0.644243,0.059490,0.626158,0.046504
36,sar_resnet31,0.642488,0.063353,0.599335,0.033466
11,vgg16,0.642426,0.060879,0.599421,0.037921
15,resnet18,0.639840,0.070495,0.596897,0.051899
0,trocr-small-stage1,0.632112,0.060356,0.607617,0.038453
10,alexnet,0.628356,0.047669,0.586410,0.031051
1,trocr-small-handwritten,0.620567,0.054739,0.578861,0.035102
8,crnn_vgg16_bn,0.608036,0.071217,0.579119,0.043313
35,crnn_mobilenet,0.600739,0.047680,0.587069,0.028292
9,vitstr_base,0.600000,0.060324,0.570006,0.041436
68,vitstr_small_224,0.559113,0.034883,0.555610,0.027777
67,vitstr_base_224,0.548553,0.039505,0.555142,0.037197

Saved table image to: df_standard_patches_table_sig4.png

# standard patches single

In [9]:
experiment='outputs\\results_standard_patches_single.json'
df_standard_patches_single=process_results(experiment, df_pre_patch,name_suffix='single',box_and_whiskers=False)
experiment_results['standard_patches_single'] = df_standard_patches_single

In [10]:
setting_display_options()
display(df_standard_patches_single.sort_values(by='accuracies_single', ascending=False))
#save_table_as_image(df_standard_patches,by_column='accuracies_single',significant_digits=4)

,FE model,accuracies_single,accuracies_std_single,ind_accuracies_single,ind_accuracies_std_single
71,clip-vit-large-patch14-inter,0.735099,0.050086,0.735099,0.050086
64,BEiT-Large-inter,0.717180,0.049545,0.717180,0.049545
47,convnext_base,0.692180,0.050186,0.692180,0.050186
45,efficientnet_v2_s,0.690579,0.068087,0.690579,0.068087
34,linknet_resnet18,0.688485,0.053955,0.688485,0.053955
18,swin_s,0.687716,0.055332,0.687716,0.055332
70,convnext_large-inter,0.684175,0.056901,0.684175,0.056901
13,trocr-large-stage1,0.681589,0.044779,0.681589,0.044779
74,trocr-large-stage1-inter,0.681496,0.048161,0.681496,0.048161
22,BEiT-Base,0.677371,0.038426,0.677371,0.038426
46,convnext_large,0.677094,0.062795,0.677094,0.062795
17,swin_b,0.676108,0.077101,0.676108,0.077101
19,DeiT-Small,0.670105,0.068560,0.670105,0.068560
73,trocr-large-handwritten-inter,0.669089,0.048219,0.669089,0.048219
28,vit-large-patch16-224-in21k,0.668381,0.061062,0.668381,0.061062
48,convnext_small,0.667334,0.049463,0.667334,0.049463
5,clip-vit-large-patch14,0.666841,0.037164,0.666841,0.037164
21,DeiT-Base,0.666318,0.069306,0.666318,0.069306
14,trocr-base-stage1,0.662223,0.063761,0.662223,0.063761
29,vit-huge-patch14-224-in21k,0.661022,0.044294,0.661022,0.044294
63,BEiT-Large,0.656989,0.025901,0.656989,0.025901
62,linknet_resnet50,0.656589,0.059381,0.656589,0.059381
27,vit-base-patch32-224-in21k,0.653079,0.050038,0.653079,0.050038
72,crnn_mobilenet_224-inter,0.652894,0.065468,0.652894,0.065468
69,dresnet50-inter,0.652094,0.060401,0.652094,0.060401
76,crnn_vgg16_bn_224-inter,0.651909,0.062659,0.651909,0.062659
59,regnet_y_32,0.650554,0.027133,0.650554,0.027133
7,dresnet50,0.650216,0.065795,0.650216,0.065795
25,clip-vit-large-patch14-un,0.649507,0.049691,0.649507,0.049691
16,DeiT-Tiny,0.648584,0.055739,0.648584,0.055739
52,resnet34_layer2,0.648522,0.052846,0.648522,0.052846
58,regnet_y_128,0.648153,0.041022,0.648153,0.041022
56,regnet_x_32,0.647044,0.049282,0.647044,0.049282
31,db_mobilenet,0.646952,0.042757,0.646952,0.042757
20,DeiT-Small-Dist,0.646028,0.054670,0.646028,0.054670
51,resnet34_layer3,0.644982,0.061756,0.644982,0.061756
50,mobilenet_v3_large,0.644027,0.060637,0.644027,0.060637
4,trocr-base-handwritten,0.640887,0.065829,0.640887,0.065829
43,maxvit,0.639778,0.048617,0.639778,0.048617
23,clip-vit-base-patch16,0.639039,0.079754,0.639039,0.079754
44,efficientnet_v2_l,0.637069,0.050723,0.637069,0.050723
49,mobilenet_v3_small,0.636145,0.055334,0.636145,0.055334
26,vit-base-patch16-224,0.635653,0.052098,0.635653,0.052098
66,crnn_vgg16_bn_224,0.635252,0.079887,0.635252,0.079887
40,densenet201,0.629372,0.036222,0.629372,0.036222
75,DeiT-Tiny-inter,0.628294,0.045891,0.628294,0.045891
3,vit-base-patch16-224-in21k,0.627617,0.054226,0.627617,0.054226
38,densenet161,0.627463,0.061006,0.627463,0.061006
53,resnet34_layer1,0.625862,0.057852,0.625862,0.057852
42,vgg16_512,0.625647,0.066482,0.625647,0.066482
39,densenet121,0.625000,0.058525,0.625000,0.058525
24,clip-vit-base-patch32,0.624169,0.061578,0.624169,0.061578
54,resnet101,0.623799,0.057719,0.623799,0.057719
65,sar_resnet31_224,0.620105,0.059099,0.620105,0.059099
41,vgg11,0.619889,0.098543,0.619889,0.098543
6,trocr-large-handwritten,0.617611,0.064840,0.617611,0.064840
2,resnet50,0.616749,0.051361,0.616749,0.051361
57,regnet_x_3_2,0.613239,0.061412,0.613239,0.061412
55,resnet34,0.607143,0.036120,0.607143,0.036120
61,inception_net,0.606281,0.047522,0.606281,0.047522
32,crnn_mobilenet_224,0.606004,0.050926,0.606004,0.050926
12,googlenet,0.605788,0.063663,0.605788,0.063663
0,trocr-small-stage1,0.599569,0.056082,0.599569,0.056082
60,regnet_y_3_2,0.598060,0.064443,0.598060,0.064443
36,sar_resnet31,0.595690,0.053810,0.595690,0.053810
10,alexnet,0.594858,0.028978,0.594858,0.028978
33,linknet_resnet50_224,0.594643,0.050763,0.594643,0.050763
37,alexnet_gap,0.590887,0.062958,0.590887,0.062958
30,vitstr_small,0.586730,0.022303,0.586730,0.022303
15,resnet18,0.586022,0.064168,0.586022,0.064168
68,vitstr_small_224,0.575800,0.057764,0.575800,0.057764
11,vgg16,0.575277,0.043785,0.575277,0.043785
35,crnn_mobilenet,0.573615,0.037516,0.573615,0.037516
67,vitstr_base_224,0.573307,0.066807,0.573307,0.066807
8,crnn_vgg16_bn,0.564871,0.065176,0.564871,0.065176
9,vitstr_base,0.548892,0.035429,0.548892,0.035429
1,trocr-small-handwritten,0.527863,0.043398,0.527863,0.043398

# standard body

In [11]:
experiment='outputs\\results_standard_body.json'
df_standard_body=process_results(experiment, df_pre_patch,name_suffix='body',box_and_whiskers=False)
experiment_results['standard_body'] = df_standard_body
setting_display_options()
display(df_standard_body.sort_values(by='accuracies_body', ascending=False))

,FE model,accuracies_body,accuracies_std_body,ind_accuracies_body,ind_accuracies_std_body
64,BEiT-Large-inter,0.731927,0.044698,0.731927,0.044698
65,clip-vit-large-patch14-inter,0.723430,0.046405,0.723430,0.046405
74,dresnet50-inter,0.699076,0.070381,0.699076,0.070381
44,convnext_base,0.696521,0.065179,0.696521,0.065179
17,swin_b,0.689532,0.023798,0.689532,0.023798
43,convnext_large,0.689409,0.062039,0.689409,0.062039
45,convnext_small,0.685099,0.038074,0.685099,0.038074
16,dresnet50,0.684791,0.055032,0.684791,0.055032
53,regnet_x_32,0.678849,0.051128,0.678849,0.051128
73,convnext_large-inter,0.677956,0.042740,0.677956,0.042740
59,linknet_resnet18,0.677063,0.056302,0.677063,0.056302
0,vit-base-patch16-224-in21k,0.671921,0.049750,0.671921,0.049750
71,trocr-large-handwritten-inter,0.671644,0.047756,0.671644,0.047756
56,regnet_y_32,0.671552,0.040852,0.671552,0.040852
19,DeiT-Small,0.669212,0.055210,0.669212,0.055210
51,resnet101,0.668042,0.055446,0.668042,0.055446
41,efficientnet_v2_l,0.665610,0.058877,0.665610,0.058877
22,BEiT-Base,0.664840,0.052301,0.664840,0.052301
62,linknet_resnet50,0.664347,0.074135,0.664347,0.074135
18,swin_s,0.661915,0.057711,0.661915,0.057711
20,DeiT-Small-Dist,0.661761,0.048035,0.661761,0.048035
21,DeiT-Base,0.660191,0.060538,0.660191,0.060538
47,mobilenet_v3_large,0.659360,0.061809,0.659360,0.061809
76,crnn_vgg16_bn_224-inter,0.659236,0.065920,0.659236,0.065920
63,BEiT-Large,0.657635,0.055780,0.657635,0.055780
38,vgg11,0.657451,0.043094,0.657451,0.043094
15,DeiT-Tiny,0.655881,0.034913,0.655881,0.034913
29,vit-huge-patch14-224-in21k,0.655757,0.060379,0.655757,0.060379
42,efficientnet_v2_s,0.655573,0.049640,0.655573,0.049640
23,clip-vit-base-patch16,0.652986,0.043341,0.652986,0.043341
72,trocr-large-stage1-inter,0.652155,0.081614,0.652155,0.081614
1,trocr-base-handwritten,0.650585,0.046502,0.650585,0.046502
49,resnet34_layer2,0.650523,0.033511,0.650523,0.033511
57,regnet_y_3_2,0.650216,0.049496,0.650216,0.049496
3,clip-vit-large-patch14,0.649723,0.057832,0.649723,0.057832
25,clip-vit-large-patch14-un,0.648984,0.047510,0.648984,0.047510
26,vit-base-patch16-224,0.648768,0.028092,0.648768,0.028092
75,DeiT-Tiny-inter,0.647937,0.034757,0.647937,0.034757
27,vit-base-patch32-224-in21k,0.646983,0.052310,0.646983,0.052310
55,regnet_y_128,0.646952,0.050043,0.646952,0.050043
28,vit-large-patch16-224-in21k,0.644335,0.050230,0.644335,0.050230
6,trocr-large-handwritten,0.643381,0.049440,0.643381,0.049440
36,densenet121,0.643196,0.050404,0.643196,0.050404
66,crnn_mobilenet_224-inter,0.640702,0.043958,0.640702,0.043958
2,resnet50,0.637808,0.046869,0.637808,0.046869
37,densenet201,0.634267,0.050579,0.634267,0.050579
24,clip-vit-base-patch32,0.632666,0.036071,0.632666,0.036071
52,resnet34,0.632574,0.045135,0.632574,0.045135
34,alexnet_gap,0.631342,0.041169,0.631342,0.041169
48,resnet34_layer3,0.626724,0.042375,0.626724,0.042375
9,trocr-large-stage1,0.626509,0.050502,0.626509,0.050502
39,vgg16_512,0.626293,0.060211,0.626293,0.060211
12,vgg16,0.624600,0.058328,0.624600,0.058328
54,regnet_x_3_2,0.623953,0.049027,0.623953,0.049027
35,densenet161,0.622752,0.069964,0.622752,0.069964
60,linknet_resnet50_224,0.620844,0.049849,0.620844,0.049849
46,mobilenet_v3_small,0.619366,0.054756,0.619366,0.054756
68,crnn_vgg16_bn_224,0.619181,0.064555,0.619181,0.064555
40,maxvit,0.618473,0.045089,0.618473,0.045089
10,trocr-base-stage1,0.617642,0.073032,0.617642,0.073032
58,inception_net,0.617457,0.053998,0.617457,0.053998
4,trocr-small-stage1,0.610499,0.056704,0.610499,0.056704
50,resnet34_layer1,0.609729,0.033041,0.609729,0.033041
13,googlenet,0.609514,0.056135,0.609514,0.056135
5,trocr-small-handwritten,0.603849,0.041053,0.603849,0.041053
67,sar_resnet31_224,0.602371,0.054299,0.602371,0.054299
14,resnet18,0.583159,0.057397,0.583159,0.057397
32,crnn_mobilenet,0.583097,0.028666,0.583097,0.028666
31,crnn_mobilenet_224,0.578787,0.057710,0.578787,0.057710
61,db_mobilenet,0.575647,0.067818,0.575647,0.067818
30,vitstr_small,0.561823,0.047044,0.561823,0.047044
69,vitstr_base_224,0.559206,0.030040,0.559206,0.030040
70,vitstr_small_224,0.555511,0.034438,0.555511,0.034438
11,alexnet,0.554680,0.039258,0.554680,0.039258
7,crnn_vgg16_bn,0.547014,0.052048,0.547014,0.052048
33,sar_resnet31,0.546767,0.041219,0.546767,0.041219
8,vitstr_base,0.536238,0.036906,0.536238,0.036906

# generalization

In [12]:
experiment='outputs\\results_standard_patches_generalization.json'
df_generalization=process_generalization_results(experiment, df_pre_patch,name_suffix='standard',box_and_whiskers=False)
experiment_results['generalization_standard'] = df_generalization
setting_display_options()
display(df_generalization.sort_values(by='generalization_standard', ascending=False))

Index(['FE model', 'type', 'train_on_language', 'cross_val_accuracies',
       'cross_val_subgroup_accuracies', 'individual_accuracies',
       'ensembled_weighted_accuracies', 'arabic,all_individual_accuracies',
       'arabic,all_ensembled_weighted_accuracies',
       'english,all_individual_accuracies',
       'english,all_ensembled_weighted_accuracies'],
      dtype='object')

,FE model,generalization_standard,generalization_std_standard,generalization_ind_standard,generalization_ind_std_standard
12,clip-vit-large-patch14,0.194089,0.094664,0.148590,0.094586
29,dresnet50,0.191379,0.077655,0.137260,0.061335
10,clip-vit-base-patch16,0.182328,0.110882,0.145954,0.078400
11,clip-vit-base-patch32,0.180480,0.091767,0.133590,0.060296
36,linknet_resnet50,0.174384,0.105602,0.147796,0.088262
43,regnet_y_128,0.172999,0.084668,0.117457,0.054561
35,linknet_resnet18,0.166225,0.101330,0.137931,0.079276
30,dresnet50-inter,0.159729,0.089944,0.123658,0.068239
50,resnet34_layer2,0.155850,0.083837,0.125099,0.081556
23,crnn_vgg16_bn_224,0.153849,0.097068,0.105911,0.080334
1,BEiT-Large,0.151724,0.101445,0.100979,0.076872
61,trocr-large-stage1,0.150647,0.105977,0.127143,0.090580
14,clip-vit-large-patch14-un,0.149723,0.072611,0.112063,0.053333
41,regnet_x_32,0.147968,0.090487,0.075794,0.073130
18,convnext_small,0.145105,0.110211,0.112826,0.091390
24,crnn_vgg16_bn_224-inter,0.140794,0.078626,0.102303,0.074368
38,maxvit,0.139224,0.097896,0.092389,0.061362
54,sar_resnet31_224,0.136176,0.096101,0.104415,0.073015
37,linknet_resnet50_224,0.136176,0.100537,0.083695,0.080474
2,BEiT-Large-inter,0.133621,0.076265,0.095536,0.065845
0,BEiT-Base,0.133005,0.122325,0.083134,0.088556
45,regnet_y_3_2,0.130757,0.117771,0.096632,0.080580
26,densenet121,0.129033,0.099990,0.086219,0.078278
60,trocr-large-handwritten-inter,0.128664,0.077105,0.079310,0.062879
17,convnext_large-inter,0.128356,0.081906,0.094550,0.070188
15,convnext_base,0.124877,0.106283,0.087913,0.079494
56,swin_s,0.121275,0.115644,0.072143,0.084095
69,vit-base-patch16-224-in21k,0.117888,0.082180,0.086743,0.060937
47,resnet18,0.117734,0.081398,0.062340,0.061548
52,resnet50,0.116995,0.099948,0.074557,0.077104
32,efficientnet_v2_s,0.114163,0.114929,0.070677,0.069689
65,vgg11,0.113177,0.083481,0.076447,0.055575
70,vit-base-patch32-224-in21k,0.113177,0.085011,0.079261,0.074217
25,db_mobilenet,0.112254,0.098048,0.083331,0.068653
51,resnet34_layer3,0.112223,0.080409,0.085111,0.060136
58,trocr-base-stage1,0.109821,0.108022,0.081034,0.079234
62,trocr-large-stage1-inter,0.109144,0.120605,0.070025,0.084476
71,vit-huge-patch14-224-in21k,0.108621,0.087876,0.078399,0.064168
20,crnn_mobilenet_224,0.107266,0.088437,0.072611,0.072719
39,mobilenet_v3_large,0.106158,0.078014,0.065400,0.050713
67,vgg16_512,0.101663,0.073825,0.069723,0.059357
6,DeiT-Tiny,0.100893,0.080453,0.061053,0.056080
68,vit-base-patch16-224,0.100431,0.068380,0.074704,0.049939
16,convnext_large,0.100185,0.111059,0.069680,0.083612
34,inception_net,0.097691,0.113788,0.055505,0.074912
7,DeiT-Tiny-inter,0.093812,0.081944,0.070062,0.067589
9,alexnet_gap,0.093781,0.077258,0.041607,0.056747
44,regnet_y_32,0.092180,0.092161,0.060437,0.064507
13,clip-vit-large-patch14-inter,0.092149,0.095837,0.065425,0.070194
46,resnet101,0.091964,0.091332,0.049741,0.065137
4,DeiT-Small,0.091318,0.087471,0.052118,0.052475
28,densenet201,0.087038,0.085192,0.051028,0.050352
66,vgg16,0.085653,0.093458,0.049828,0.055928
33,googlenet,0.082851,0.096303,0.047869,0.076444
59,trocr-large-handwritten,0.082204,0.080880,0.058424,0.052320
31,efficientnet_v2_l,0.079156,0.081273,0.060634,0.057754
5,DeiT-Small-Dist,0.078171,0.093510,0.046459,0.061499
48,resnet34,0.076755,0.089278,0.040517,0.052934
3,DeiT-Base,0.073615,0.099522,0.050911,0.059182
22,crnn_vgg16_bn,0.071644,0.081347,0.042334,0.056622
40,mobilenet_v3_small,0.071367,0.083181,0.056195,0.061669
55,swin_b,0.068288,0.079038,0.047432,0.064667
72,vit-large-patch16-224-in21k,0.068073,0.107986,0.060320,0.071010
75,vitstr_small,0.059452,0.069883,0.043171,0.056566
27,densenet161,0.057697,0.115473,0.049464,0.086572
42,regnet_x_3_2,0.054772,0.077295,0.040222,0.055798
57,trocr-base-handwritten,0.050246,0.088695,0.040111,0.056164
21,crnn_mobilenet_224-inter,0.047537,0.061649,0.053984,0.050408
76,vitstr_small_224,0.039070,0.087131,0.017943,0.054515
19,crnn_mobilenet,0.038793,0.094547,0.029243,0.066310
64,trocr-small-stage1,0.024908,0.106551,0.020443,0.065152
73,vitstr_base,0.024507,0.091421,0.016773,0.052100
63,trocr-small-handwritten,0.023892,0.083124,0.025142,0.053364
74,vitstr_base_224,0.019243,0.093441,0.011250,0.058036
49,resnet34_layer1,0.015887,0.064599,0.011207,0.056563
8,alexnet,0.013147,0.081626,0.004477,0.058876
53,sar_resnet31,0.010499,0.077730,0.021724,0.044127

# aggregated

In [17]:
# Merge all dataframes in experiment_results on 'FE model' column
df_aggregated = None

for key, df in experiment_results.items():
    if df_aggregated is None:
        df_aggregated = df.copy()
    else:
        df_aggregated = df_aggregated.merge(df, on='FE model', how='outer')

display(df_aggregated)

,FE model,accuracies_standard,accuracies_std_standard,ind_accuracies_standard,ind_accuracies_std_standard,accuracies_single,accuracies_std_single,ind_accuracies_single,ind_accuracies_std_single,accuracies_body,accuracies_std_body,ind_accuracies_body,ind_accuracies_std_body,generalization_standard,generalization_std_standard,generalization_ind_standard,generalization_ind_std_standard
0,BEiT-Base,0.765025,0.055745,0.711188,0.036050,0.677371,0.038426,0.677371,0.038426,0.664840,0.052301,0.664840,0.052301,0.133005,0.122325,0.083134,0.088556
1,BEiT-Large,0.767826,0.061211,0.718713,0.047689,0.656989,0.025901,0.656989,0.025901,0.657635,0.055780,0.657635,0.055780,0.151724,0.101445,0.100979,0.076872
2,BEiT-Large-inter,0.766041,0.051911,0.729649,0.037044,0.717180,0.049545,0.717180,0.049545,0.731927,0.044698,0.731927,0.044698,0.133621,0.076265,0.095536,0.065845
3,DeiT-Base,0.697660,0.020155,0.651059,0.018927,0.666318,0.069306,0.666318,0.069306,0.660191,0.060538,0.660191,0.060538,0.073615,0.099522,0.050911,0.059182
4,DeiT-Small,0.730357,0.051938,0.673528,0.039391,0.670105,0.068560,0.670105,0.068560,0.669212,0.055210,0.669212,0.055210,0.091318,0.087471,0.052118,0.052475
5,DeiT-Small-Dist,0.713300,0.049624,0.668165,0.043527,0.646028,0.054670,0.646028,0.054670,0.661761,0.048035,0.661761,0.048035,0.078171,0.093510,0.046459,0.061499
6,DeiT-Tiny,0.684083,0.060543,0.647315,0.045750,0.648584,0.055739,0.648584,0.055739,0.655881,0.034913,0.655881,0.034913,0.100893,0.080453,0.061053,0.056080
7,DeiT-Tiny-inter,0.690425,0.051063,0.662580,0.045622,0.628294,0.045891,0.628294,0.045891,0.647937,0.034757,0.647937,0.034757,0.093812,0.081944,0.070062,0.067589
8,alexnet,0.628356,0.047669,0.586410,0.031051,0.594858,0.028978,0.594858,0.028978,0.554680,0.039258,0.554680,0.039258,0.013147,0.081626,0.004477,0.058876
9,alexnet_gap,0.663670,0.075532,0.624643,0.047010,0.590887,0.062958,0.590887,0.062958,0.631342,0.041169,0.631342,0.041169,0.093781,0.077258,0.041607,0.056747
10,clip-vit-base-patch16,0.730388,0.045668,0.677531,0.045884,0.639039,0.079754,0.639039,0.079754,0.652986,0.043341,0.652986,0.043341,0.182328,0.110882,0.145954,0.078400
11,clip-vit-base-patch32,0.689501,0.041031,0.656361,0.035622,0.624169,0.061578,0.624169,0.061578,0.632666,0.036071,0.632666,0.036071,0.180480,0.091767,0.133590,0.060296
12,clip-vit-large-patch14,0.723307,0.033247,0.692605,0.037414,0.666841,0.037164,0.666841,0.037164,0.649723,0.057832,0.649723,0.057832,0.194089,0.094664,0.148590,0.094586
13,clip-vit-large-patch14-inter,0.774015,0.051471,0.740062,0.033951,0.735099,0.050086,0.735099,0.050086,0.723430,0.046405,0.723430,0.046405,0.092149,0.095837,0.065425,0.070194
14,clip-vit-large-patch14-un,0.741010,0.044030,0.685979,0.045204,0.649507,0.049691,0.649507,0.049691,0.648984,0.047510,0.648984,0.047510,0.149723,0.072611,0.112063,0.053333
15,convnext_base,0.724415,0.076435,0.690203,0.053959,0.692180,0.050186,0.692180,0.050186,0.696521,0.065179,0.696521,0.065179,0.124877,0.106283,0.087913,0.079494
16,convnext_large,0.734883,0.061863,0.698615,0.041903,0.677094,0.062795,0.677094,0.062795,0.689409,0.062039,0.689409,0.062039,0.100185,0.111059,0.069680,0.083612
17,convnext_large-inter,0.727802,0.052981,0.700117,0.043353,0.684175,0.056901,0.684175,0.056901,0.677956,0.042740,0.677956,0.042740,0.128356,0.081906,0.094550,0.070188
18,convnext_small,0.718812,0.049091,0.690339,0.044065,0.667334,0.049463,0.667334,0.049463,0.685099,0.038074,0.685099,0.038074,0.145105,0.110211,0.112826,0.091390
19,crnn_mobilenet,0.600739,0.047680,0.587069,0.028292,0.573615,0.037516,0.573615,0.037516,0.583097,0.028666,0.583097,0.028666,0.038793,0.094547,0.029243,0.066310
20,crnn_mobilenet_224,0.644243,0.059490,0.626158,0.046504,0.606004,0.050926,0.606004,0.050926,0.578787,0.057710,0.578787,0.057710,0.107266,0.088437,0.072611,0.072719
21,crnn_mobilenet_224-inter,0.670751,0.056131,0.646176,0.051307,0.652894,0.065468,0.652894,0.065468,0.640702,0.043958,0.640702,0.043958,0.047537,0.061649,0.053984,0.050408
22,crnn_vgg16_bn,0.608036,0.071217,0.579119,0.043313,0.564871,0.065176,0.564871,0.065176,0.547014,0.052048,0.547014,0.052048,0.071644,0.081347,0.042334,0.056622
23,crnn_vgg16_bn_224,0.679526,0.093259,0.641958,0.075816,0.635252,0.079887,0.635252,0.079887,0.619181,0.064555,0.619181,0.064555,0.153849,0.097068,0.105911,0.080334
24,crnn_vgg16_bn_224-inter,0.704495,0.068534,0.681170,0.060752,0.651909,0.062659,0.651909,0.062659,0.659236,0.065920,0.659236,0.065920,0.140794,0.078626,0.102303,0.074368
25,db_mobilenet,0.664717,0.056248,0.643898,0.043428,0.646952,0.042757,0.646952,0.042757,0.575647,0.067818,0.575647,0.067818,0.112254,0.098048,0.083331,0.068653
26,densenet121,0.677001,0.069482,0.639514,0.046574,0.625000,0.058525,0.625000,0.058525,0.643196,0.050404,0.643196,0.050404,0.129033,0.099990,0.086219,0.078278
27,densenet161,0.678110,0.070751,0.636281,0.044350,0.627463,0.061006,0.627463,0.061006,0.622752,0.069964,0.622752,0.069964,0.057697,0.115473,0.049464,0.086572
28,densenet201,0.689840,0.057988,0.645677,0.037803,0.629372,0.036222,0.629372,0.036222,0.634267,0.050579,0.634267,0.050579,0.087038,0.085192,0.051028,0.050352
29,dresnet50,0.715148,0.050710,0.663356,0.045230,0.650216,0.065795,0.650216,0.065795,0.684791,0.055032,0.684791,0.055032,0.191379,0.077655,0.137260,0.061335
30,dresnet50-inter,0.709052,0.049691,0.683947,0.047230,0.652094,0.060401,0.652094,0.060401,0.699076,0.070381,0.699076,0.070381,0.159729,0.089944,0.123658,0.068239
31,efficientnet_v2_l,0.706312,0.042903,0.671361,0.039950,0.637069,0.050723,0.637069,0.050723,0.665610,0.058877,0.665610,0.058877,0.079156,0.081273,0.060634,0.057754
32,efficientnet_v2_s,0.727894,0.061601,0.689680,0.052321,0.690579,0.068087,0.690579,0.068087,0.655573,0.049640,0.655573,0.049640,0.114163,0.114929,0.070677,0.069689
33,googlenet,0.663547,0.078984,0.625708,0.056641,0.605788,0.063663,0.605788,0.063663,0.609514,0.056135,0.609514,0.056135,0.082851,0.096303,0.047869,0.076444
34,inception_net,0.678879,0.050632,0.629027,0.043898,0.606281,0.047522,0.606281,0.047522,0.617457,0.053998,0.617457,0.053998,0.097691,0.113788,0.055505,0.074912
35,linknet_resnet18,0.716810,0.064331,0.684366,0.045758,0.688485,0.053955,0.688485,0.053955,0.677063,0.056302,0.677063,0.056302,0.166225,0.101330,0.137931,0.079276
36,linknet_resnet50,0.693103,0.051261,0.664107,0.049212,0.656589,0.059381,0.656589,0.059381,0.664347,0.074135,0.664347,0.074135,0.174384,0.105602,0.147796,0.088262
37,linknet_resnet50_224,0.666349,0.056514,0.612457,0.051629,0.594643,0.050763,0.594643,0.050763,0.620844,0.049849,0.620844,0.049849,0.136176,0.100537,0.083695,0.080474
38,maxvit,0.683436,0.068781,0.646952,0.051936,0.639778,0.048617,0.639778,0.048617,0.618473,0.045089,0.618473,0.045089,0.139224,0.097896,0.092389,0.061362
39,mobilenet_v3_large,0.708744,0.074062,0.664828,0.055492,0.644027,0.060637,0.644027,0.060637,0.659360,0.061809,0.659360,0.061809,0.106158,0.078014,0.065400,0.050713
40,mobilenet_v3_small,0.680388,0.065858,0.647365,0.052892,0.636145,0.055334,0.636145,0.055334,0.619366,0.054756,0.619366,0.054756,0.071367,0.083181,0.056195,0.061669
41,regnet_x_32,0.709236,0.062118,0.659963,0.047352,0.647044,0.049282,0.647044,0.049282,0.678849,0.051128,0.678849,0.051128,0.147968,0.090487,0.075794,0.073130
42,regnet_x_3_2,0.670720,0.057820,0.623929,0.040948,0.613239,0.061412,0.613239,0.061412,0.623953,0.049027,0.623953,0.049027,0.054772,0.077295,0.040222,0.055798
43,regnet_y_128,0.683528,0.049835,0.631459,0.032355,0.648153,0.041022,0.648153,0.041022,0.646952,0.050043,0.646952,0.050043,0.172999,0.084668,0.117457,0.054561
44,regnet_y_32,0.691533,0.056980,0.652469,0.046400,0.650554,0.027133,0.650554,0.027133,0.671552,0.040852,0.671552,0.040852,0.092180,0.092161,0.060437,0.064507
45,regnet_y_3_2,0.693042,0.058527,0.644070,0.051154,0.598060,0.064443,0.598060,0.064443,0.650216,0.049496,0.650216,0.049496,0.130757,0.117771,0.096632,0.080580
46,resnet101,0.682574,0.059557,0.650179,0.047928,0.623799,0.057719,0.623799,0.057719,0.668042,0.055446,0.668042,0.055446,0.091964,0.091332,0.049741,0.065137
47,resnet18,0.639840,0.070495,0.596897,0.051899,0.586022,0.064168,0.586022,0.064168,0.583159,0.057397,0.583159,0.057397,0.117734,0.081398,0.062340,0.061548
48,resnet34,0.665456,0.062880,0.610400,0.047225,0.607143,0.036120,0.607143,0.036120,0.632574,0.045135,0.632574,0.045135,0.076755,0.089278,0.040517,0.052934
49,resnet34_layer1,0.664932,0.053666,0.649113,0.048336,0.625862,0.057852,0.625862,0.057852,0.609729,0.033041,0.609729,0.033041,0.015887,0.064599,0.011207,0.056563
50,resnet34_layer2,0.701786,0.062526,0.671201,0.057839,0.648522,0.052846,0.648522,0.052846,0.650523,0.033511,0.650523,0.033511,0.155850,0.083837,0.125099,0.081556
51,resnet34_layer3,0.684975,0.071525,0.658768,0.048379,0.644982,0.061756,0.644982,0.061756,0.626724,0.042375,0.626724,0.042375,0.112223,0.080409,0.085111,0.060136
52,resnet50,0.688608,0.056224,0.643288,0.039782,0.616749,0.051361,0.616749,0.051361,0.637808,0.046869,0.637808,0.046869,0.116995,0.099948,0.074557,0.077104
53,sar_resnet31,0.642488,0.063353,0.599335,0.033466,0.595690,0.053810,0.595690,0.053810,0.546767,0.041219,0.546767,0.041219,0.010499,0.077730,0.021724,0.044127
54,sar_resnet31_224,0.647814,0.075329,0.625844,0.056769,0.620105,0.059099,0.620105,0.059099,0.602371,0.054299,0.602371,0.054299,0.136176,0.096101,0.104415,0.073015
55,swin_b,0.723337,0.058295,0.690659,0.046705,0.676108,0.077101,0.676108,0.077101,0.689532,0.023798,0.689532,0.023798,0.068288,0.079038,0.047432,0.064667
56,swin_s,0.729526,0.062252,0.687377,0.044621,0.687716,0.055332,0.687716,0.055332,0.661915,0.057711,0.661915,0.057711,0.121275,0.115644,0.072143,0.084095
57,trocr-base-handwritten,0.664563,0.065464,0.648744,0.050904,0.640887,0.065829,0.640887,0.065829,0.650585,0.046502,0.650585,0.046502,0.050246,0.088695,0.040111,0.056164
58,trocr-base-stage1,0.710037,0.036919,0.678584,0.043617,0.662223,0.063761,0.662223,0.063761,0.617642,0.073032,0.617642,0.073032,0.109821,0.108022,0.081034,0.079234
59,trocr-large-handwritten,0.711700,0.048113,0.663510,0.047219,0.617611,0.064840,0.617611,0.064840,0.643381,0.049440,0.643381,0.049440,0.082204,0.080880,0.058424,0.052320
60,trocr-large-handwritten-inter,0.752555,0.052081,0.693836,0.042002,0.669089,0.048219,0.669089,0.048219,0.671644,0.047756,0.671644,0.047756,0.128664,0.077105,0.079310,0.062879
61,trocr-large-stage1,0.724969,0.064788,0.689101,0.056321,0.681589,0.044779,0.681589,0.044779,0.626509,0.050502,0.626509,0.050502,0.150647,0.105977,0.127143,0.090580
62,trocr-large-stage1-inter,0.734144,0.070820,0.694310,0.049490,0.681496,0.048161,0.681496,0.048161,0.652155,0.081614,0.652155,0.081614,0.109144,0.120605,0.070025,0.084476
63,trocr-small-handwritten,0.620567,0.054739,0.578861,0.035102,0.527863,0.043398,0.527863,0.043398,0.603849,0.041053,0.603849,0.041053,0.023892,0.083124,0.025142,0.053364
64,trocr-small-stage1,0.632112,0.060356,0.607617,0.038453,0.599569,0.056082,0.599569,0.056082,0.610499,0.056704,0.610499,0.056704,0.024908,0.106551,0.020443,0.065152
65,vgg11,0.670782,0.062349,0.639009,0.060769,0.619889,0.098543,0.619889,0.098543,0.657451,0.043094,0.657451,0.043094,0.113177,0.083481,0.076447,0.055575
66,vgg16,0.642426,0.060879,0.599421,0.037921,0.575277,0.043785,0.575277,0.043785,0.624600,0.058328,0.624600,0.058328,0.085653,0.093458,0.049828,0.055928
67,vgg16_512,0.668966,0.074452,0.634212,0.050338,0.625647,0.066482,0.625647,0.066482,0.626293,0.060211,0.626293,0.060211,0.101663,0.073825,0.069723,0.059357
68,vit-base-patch16-224,0.721829,0.045587,0.660764,0.035632,0.635653,0.052098,0.635653,0.052098,0.648768,0.028092,0.648768,0.028092,0.100431,0.068380,0.074704,0.049939
69,vit-base-patch16-224-in21k,0.712685,0.040415,0.667488,0.042831,0.627617,0.054226,0.627617,0.054226,0.671921,0.049750,0.671921,0.049750,0.117888,0.082180,0.086743,0.060937
70,vit-base-patch32-224-in21k,0.698399,0.028605,0.671712,0.030933,0.653079,0.050038,0.653079,0.050038,0.646983,0.052310,0.646983,0.052310,0.113177,0.085011,0.079261,0.074217
71,vit-huge-patch14-224-in21k,0.706158,0.059311,0.685751,0.042826,0.661022,0.044294,0.661022,0.044294,0.655757,0.060379,0.655757,0.060379,0.108621,0.087876,0.078399,0.064168
72,vit-large-patch16-224-in21k,0.696798,0.046043,0.667371,0.026762,0.668381,0.061062,0.668381,0.061062,0.644335,0.050230,0.644335,0.050230,0.068073,0.107986,0.060320,0.071010
73,vitstr_base,0.600000,0.060324,0.570006,0.041436,0.548892,0.035429,0.548892,0.035429,0.536238,0.036906,0.536238,0.036906,0.024507,0.091421,0.016773,0.052100
74,vitstr_base_224,0.548553,0.039505,0.555142,0.037197,0.573307,0.066807,0.573307,0.066807,0.559206,0.030040,0.559206,0.030040,0.019243,0.093441,0.011250,0.058036
75,vitstr_small,0.653910,0.046466,0.612654,0.036995,0.586730,0.022303,0.586730,0.022303,0.561823,0.047044,0.561823,0.047044,0.059452,0.069883,0.043171,0.056566
76,vitstr_small_224,0.559113,0.034883,0.555610,0.027777,0.575800,0.057764,0.575800,0.057764,0.555511,0.034438,0.555511,0.034438,0.039070,0.087131,0.017943,0.054515

In [18]:
# Save key DataFrames with a timestamp into the results folder
timestamp = pd.Timestamp.now().strftime("%Y%m%d_%H%M%S")
results_dir = "results"
os.makedirs(results_dir, exist_ok=True)
base = f"df_aggregated_{timestamp}"
csv_path_timestamp = os.path.join(results_dir, f"{base}.csv")
csv_path_last = os.path.join(results_dir, "df_aggregated_last.csv")
df_aggregated.to_csv(csv_path_timestamp, index=False)
df_aggregated.to_csv(csv_path_last, index=False)

In [ ]:
columns=['FE model','accuracies_standard','accuracies_std_standard','ind_accuracies_standard','ind_accuracies_single'
         ,'ind_accuracies_body','generalization_standard','generalization_ind_standard']
display(df_aggregated[columns].sort_values(by='accuracies_standard', ascending=False))

,FE model,accuracies_standard,ind_accuracies_standard,ind_accuracies_single,ind_accuracies_body,generalization_standard,generalization_ind_standard
13,clip-vit-large-patch14-inter,0.774015,0.740062,0.735099,0.723430,0.092149,0.065425
1,BEiT-Large,0.767826,0.718713,0.656989,0.657635,0.151724,0.100979
2,BEiT-Large-inter,0.766041,0.729649,0.717180,0.731927,0.133621,0.095536
0,BEiT-Base,0.765025,0.711188,0.677371,0.664840,0.133005,0.083134
60,trocr-large-handwritten-inter,0.752555,0.693836,0.669089,0.671644,0.128664,0.079310
14,clip-vit-large-patch14-un,0.741010,0.685979,0.649507,0.648984,0.149723,0.112063
16,convnext_large,0.734883,0.698615,0.677094,0.689409,0.100185,0.069680
62,trocr-large-stage1-inter,0.734144,0.694310,0.681496,0.652155,0.109144,0.070025
10,clip-vit-base-patch16,0.730388,0.677531,0.639039,0.652986,0.182328,0.145954
4,DeiT-Small,0.730357,0.673528,0.670105,0.669212,0.091318,0.052118
56,swin_s,0.729526,0.687377,0.687716,0.661915,0.121275,0.072143
32,efficientnet_v2_s,0.727894,0.689680,0.690579,0.655573,0.114163,0.070677
17,convnext_large-inter,0.727802,0.700117,0.684175,0.677956,0.128356,0.094550
61,trocr-large-stage1,0.724969,0.689101,0.681589,0.626509,0.150647,0.127143
15,convnext_base,0.724415,0.690203,0.692180,0.696521,0.124877,0.087913
55,swin_b,0.723337,0.690659,0.676108,0.689532,0.068288,0.047432
12,clip-vit-large-patch14,0.723307,0.692605,0.666841,0.649723,0.194089,0.148590
68,vit-base-patch16-224,0.721829,0.660764,0.635653,0.648768,0.100431,0.074704
18,convnext_small,0.718812,0.690339,0.667334,0.685099,0.145105,0.112826
35,linknet_resnet18,0.716810,0.684366,0.688485,0.677063,0.166225,0.137931
29,dresnet50,0.715148,0.663356,0.650216,0.684791,0.191379,0.137260
5,DeiT-Small-Dist,0.713300,0.668165,0.646028,0.661761,0.078171,0.046459
69,vit-base-patch16-224-in21k,0.712685,0.667488,0.627617,0.671921,0.117888,0.086743
59,trocr-large-handwritten,0.711700,0.663510,0.617611,0.643381,0.082204,0.058424
58,trocr-base-stage1,0.710037,0.678584,0.662223,0.617642,0.109821,0.081034
41,regnet_x_32,0.709236,0.659963,0.647044,0.678849,0.147968,0.075794
30,dresnet50-inter,0.709052,0.683947,0.652094,0.699076,0.159729,0.123658
39,mobilenet_v3_large,0.708744,0.664828,0.644027,0.659360,0.106158,0.065400
31,efficientnet_v2_l,0.706312,0.671361,0.637069,0.665610,0.079156,0.060634
71,vit-huge-patch14-224-in21k,0.706158,0.685751,0.661022,0.655757,0.108621,0.078399
24,crnn_vgg16_bn_224-inter,0.704495,0.681170,0.651909,0.659236,0.140794,0.102303
50,resnet34_layer2,0.701786,0.671201,0.648522,0.650523,0.155850,0.125099
70,vit-base-patch32-224-in21k,0.698399,0.671712,0.653079,0.646983,0.113177,0.079261
3,DeiT-Base,0.697660,0.651059,0.666318,0.660191,0.073615,0.050911
72,vit-large-patch16-224-in21k,0.696798,0.667371,0.668381,0.644335,0.068073,0.060320
36,linknet_resnet50,0.693103,0.664107,0.656589,0.664347,0.174384,0.147796
45,regnet_y_3_2,0.693042,0.644070,0.598060,0.650216,0.130757,0.096632
44,regnet_y_32,0.691533,0.652469,0.650554,0.671552,0.092180,0.060437
7,DeiT-Tiny-inter,0.690425,0.662580,0.628294,0.647937,0.093812,0.070062
28,densenet201,0.689840,0.645677,0.629372,0.634267,0.087038,0.051028
11,clip-vit-base-patch32,0.689501,0.656361,0.624169,0.632666,0.180480,0.133590
52,resnet50,0.688608,0.643288,0.616749,0.637808,0.116995,0.074557
51,resnet34_layer3,0.684975,0.658768,0.644982,0.626724,0.112223,0.085111
6,DeiT-Tiny,0.684083,0.647315,0.648584,0.655881,0.100893,0.061053
43,regnet_y_128,0.683528,0.631459,0.648153,0.646952,0.172999,0.117457
38,maxvit,0.683436,0.646952,0.639778,0.618473,0.139224,0.092389
46,resnet101,0.682574,0.650179,0.623799,0.668042,0.091964,0.049741
40,mobilenet_v3_small,0.680388,0.647365,0.636145,0.619366,0.071367,0.056195
23,crnn_vgg16_bn_224,0.679526,0.641958,0.635252,0.619181,0.153849,0.105911
34,inception_net,0.678879,0.629027,0.606281,0.617457,0.097691,0.055505
27,densenet161,0.678110,0.636281,0.627463,0.622752,0.057697,0.049464
26,densenet121,0.677001,0.639514,0.625000,0.643196,0.129033,0.086219
65,vgg11,0.670782,0.639009,0.619889,0.657451,0.113177,0.076447
21,crnn_mobilenet_224-inter,0.670751,0.646176,0.652894,0.640702,0.047537,0.053984
42,regnet_x_3_2,0.670720,0.623929,0.613239,0.623953,0.054772,0.040222
67,vgg16_512,0.668966,0.634212,0.625647,0.626293,0.101663,0.069723
37,linknet_resnet50_224,0.666349,0.612457,0.594643,0.620844,0.136176,0.083695
48,resnet34,0.665456,0.610400,0.607143,0.632574,0.076755,0.040517
49,resnet34_layer1,0.664932,0.649113,0.625862,0.609729,0.015887,0.011207
25,db_mobilenet,0.664717,0.643898,0.646952,0.575647,0.112254,0.083331
57,trocr-base-handwritten,0.664563,0.648744,0.640887,0.650585,0.050246,0.040111
9,alexnet_gap,0.663670,0.624643,0.590887,0.631342,0.093781,0.041607
33,googlenet,0.663547,0.625708,0.605788,0.609514,0.082851,0.047869
75,vitstr_small,0.653910,0.612654,0.586730,0.561823,0.059452,0.043171
54,sar_resnet31_224,0.647814,0.625844,0.620105,0.602371,0.136176,0.104415
20,crnn_mobilenet_224,0.644243,0.626158,0.606004,0.578787,0.107266,0.072611
53,sar_resnet31,0.642488,0.599335,0.595690,0.546767,0.010499,0.021724
66,vgg16,0.642426,0.599421,0.575277,0.624600,0.085653,0.049828
47,resnet18,0.639840,0.596897,0.586022,0.583159,0.117734,0.062340
64,trocr-small-stage1,0.632112,0.607617,0.599569,0.610499,0.024908,0.020443
8,alexnet,0.628356,0.586410,0.594858,0.554680,0.013147,0.004477
63,trocr-small-handwritten,0.620567,0.578861,0.527863,0.603849,0.023892,0.025142
22,crnn_vgg16_bn,0.608036,0.579119,0.564871,0.547014,0.071644,0.042334
19,crnn_mobilenet,0.600739,0.587069,0.573615,0.583097,0.038793,0.029243
73,vitstr_base,0.600000,0.570006,0.548892,0.536238,0.024507,0.016773
76,vitstr_small_224,0.559113,0.555610,0.575800,0.555511,0.039070,0.017943
74,vitstr_base_224,0.548553,0.555142,0.573307,0.559206,0.019243,0.011250

# easy access

In [2]:
def reload_modules():
    import importlib
    import utils.file_IO as file_IO
    import utils.experiment_analysis_utils as experiment_analysis_utils
    
    importlib.reload(file_IO)
    importlib.reload(experiment_analysis_utils)

    return file_IO, experiment_analysis_utils
file_IO, experiment_analysis_utils = reload_modules()

In [3]:
from pandas.api.types import is_numeric_dtype

def setting_display_options():
    pd.set_option('display.max_rows', None)
    pd.set_option('display.max_columns', None)
    pd.set_option('display.width', None)
    pd.set_option('display.max_colwidth', None)


def process_results(experiment, df_pre_patch,name_suffix='standard',box_and_whiskers=True):
    df = file_IO.assemble_csv_from_log(experiment)
    df=experiment_analysis_utils.extends_with_info_from_source(df,df_pre_patch,columns=['unique name', 'type'])
    features_of_interest = ['FE model','type']
    df = df[features_of_interest+['cross_val_accuracies','cross_val_subgroup_accuracies']]
    #df_exp=expand_accuracies(df, all_ensembling_approaches,all_groups)
    df_exp = experiment_analysis_utils.get_crossval_results(df)
    #selected_accuracies = select_accuracies(all_ensembling_approaches, ['OOF','IF'], ['Mean','Generalization Gap'], ['all,all','english,all','arabic,all'])
    selected_accuracies = ['individual_accuracies', 'ensembled_weighted_accuracies']
    #print(selected_accuracies)
    #ensembling_types=['ensembled'],IF_OOF=['OOF'],metrics=['Mean'],groups=['all,all','english,all']
    df=df_exp[features_of_interest+selected_accuracies]
    accuracies=df_exp['ensembled_weighted_accuracies'].apply(lambda x: np.mean(x))
    accuracies_std=df_exp['ensembled_weighted_accuracies'].apply(lambda x: np.std(x))
    ind_accuracies=df_exp['individual_accuracies'].apply(lambda x: np.mean(x))
    ind_accuracies_std=df_exp['individual_accuracies'].apply(lambda x: np.std(x))
    df_processed = pd.DataFrame({
        'FE model': df_exp['FE model'],
        f'accuracies_{name_suffix}': accuracies,
        f'accuracies_std_{name_suffix}': accuracies_std,
        f'ind_accuracies_{name_suffix}': ind_accuracies,
        f'ind_accuracies_std_{name_suffix}': ind_accuracies_std
    })
    if box_and_whiskers:
        experiment_analysis_utils.box_and_whiskers(df, type='squares', accuracy_col='individual_accuracies',
                                                   title='Distribution of Accuracies per FE Model, standard body dataset')
    return df_processed
def process_generalization_results(experiment, df_pre_patch,name_suffix='standard',box_and_whiskers=True):
    df = file_IO.assemble_csv_from_log(experiment)
    df = experiment_analysis_utils.extends_with_info_from_source(df,df_pre_patch,columns=['unique name', 'type'])
    features_of_interest = ['FE model','type','train_on_language']
    df = df[features_of_interest+['cross_val_accuracies','cross_val_subgroup_accuracies']]
    #df_exp=expand_accuracies(df, all_ensembling_approaches,all_groups)
    df_exp = experiment_analysis_utils.get_crossval_results(df)
    print(df_exp.columns)
    #selected_accuracies = select_accuracies(all_ensembling_approaches, ['OOF','IF'], ['Mean','Generalization Gap'], ['all,all','english,all','arabic,all'])
    selected_accuracies = ['arabic,all_individual_accuracies','english,all_individual_accuracies',
                        'arabic,all_ensembled_weighted_accuracies','english,all_ensembled_weighted_accuracies']
    #print(selected_accuracies)
    #ensembling_types=['ensembled'],IF_OOF=['OOF'],metrics=['Mean'],groups=['all,all','english,all']
    df=df_exp[features_of_interest+selected_accuracies]
    df_individual = df.copy()
    df_individual['script_generalization_individual'] = df.apply(experiment_analysis_utils.script_generalization_compute_diffs, axis=1, args=('individual',))
    df_individual=experiment_analysis_utils.script_generalization_join_acc_lists(df_individual,merge_cols=['FE model','type'],columns=['script_generalization_individual'])
    df_ensemble = df.copy()
    df_ensemble['script_generalization_ensembled_weighted'] = df.apply(experiment_analysis_utils.script_generalization_compute_diffs, axis=1, args=('ensembled_weighted',))
    df_ensemble=experiment_analysis_utils.script_generalization_join_acc_lists(df_ensemble,merge_cols=['FE model','type'],columns=['script_generalization_ensembled_weighted'])
    df_merged = df_individual[['FE model', 'script_generalization_individual']].merge(
        df_ensemble[['FE model', 'script_generalization_ensembled_weighted']], 
        on='FE model', 
        how='outer'
    )
    accuracies=df_merged['script_generalization_ensembled_weighted'].apply(lambda x: np.mean(x))
    accuracies_std=df_merged['script_generalization_ensembled_weighted'].apply(lambda x: np.std(x))
    ind_accuracies=df_merged['script_generalization_individual'].apply(lambda x: np.mean(x))
    ind_accuracies_std=df_merged['script_generalization_individual'].apply(lambda x: np.std(x))
    df_processed = pd.DataFrame({
        'FE model': df_merged['FE model'],
        f'generalization_{name_suffix}': accuracies,
        f'generalization_std_{name_suffix}': accuracies_std,
        f'generalization_ind_{name_suffix}': ind_accuracies,
        f'generalization_ind_std_{name_suffix}': ind_accuracies_std
    })
    if box_and_whiskers:
        pass
    return df_processed
def save_table_as_image(df_standard_patches, by_column='accuracies',significant_digits=4):
    import matplotlib.pyplot as plt

    _sorted = df_standard_patches.sort_values(by=by_column, ascending=False).reset_index(drop=True)

    def format_sig(x, sig):
        if pd.isna(x):
            return ""
        return f"{x:.{sig}g}"

    formatted = _sorted.copy()
    for col in formatted.columns:
        if is_numeric_dtype(formatted[col]):
            formatted[col] = formatted[col].apply(lambda v: format_sig(v, significant_digits))

    rows, cols = formatted.shape
    fig_w = max(10, cols * 2.2)
    fig_h = min(40, 0.35 * rows + 1.5)

    fig, ax = plt.subplots(figsize=(fig_w, fig_h))
    ax.axis('off')

    table = ax.table(
        cellText=formatted.values,
        colLabels=formatted.columns,
        loc='center',
        cellLoc='center'
    )

    table.auto_set_font_size(False)
    table.set_fontsize(8)
    table.scale(1, 1.2)
    for (r, c), cell in table.get_celld().items():
        cell.set_edgecolor('#cccccc')
        cell.set_linewidth(0.5)
        if r == 0:
            cell.set_text_props(weight='bold')
            cell.set_facecolor('#f2f2f2')

    fig.tight_layout(pad=0.5)

    out_path = f"df_standard_patches_table_sig{significant_digits}.png"
    fig.savefig(out_path, dpi=300, bbox_inches='tight')
    plt.close(fig)
    print(f"Saved table image to: {out_path}")